Spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: e_com
      auto-index-creation: true


spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8080
  servlet:
    context-path: /api/v1



jwt:
  secret: mysecretkeymysecretkeymysecretkey
  expiration: 3600000
